# **3주차 실습 - 텍스트 표현**

** 출처 **
*   파이썬 텍스트 마이닝 완벽가이드(https://github.com/wikibook/textmining)
*   딥러닝 파이토치 교과서 - 입문부터 LLM 파인튜닝까지(https://wikidocs.net/217237)
*   딥러닝을 이용한 자연어 처리 입문(https://wikidocs.net/21707)

# **1. Bag of Words(BoW)**

## **1-1. 라이브러리 활용**

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

doc1 = '먹고 싶은 사과'
doc2 = '먹고 싶은 바나나'
doc3 = '길고 노란 바나나 바나나'
doc4 = '저는 과일이 좋아요'

docs = [doc1, doc2, doc3, doc4]

In [ ]:
# CountVectorizer 초기화
vectorizer = CountVectorizer()

# 문서를 BoW 행렬로 변환
bow_matrix = vectorizer.fit_transform(docs)

# BoW 행렬을 array로 저장
bow_scores = bow_matrix.toarray()

# 특성 이름(단어) 가져오기
feature_names = vectorizer.get_feature_names_out()

# 결과를 표시하기 위한 pandas DataFrame 생성
df_bow = pd.DataFrame(bow_scores, columns=feature_names)

# 문서 텍스트를 담은 컬럼 추가
df_bow['문서'] = docs

In [ ]:
feature_names

In [ ]:
bow_scores

In [ ]:
df_bow

## **1-2. 직접구현**

각 단어에 고유한 정수 인덱스를 부여하여 벡터를 만들고 각 단어의 등장 횟수를 기록

In [ ]:
!pip install konlpy

In [ ]:
from konlpy.tag import Okt

okt = Okt()

# 텍스트 전처리 및 BoW 생성을 위한 함수 정의
def build_bag_of_words(doc):
    # 온점 제거 및 토큰화(형태소 분석)
    doc = doc.replace('.', '')
    tokenized_document = okt.morphs(doc)

    word_to_index = {}  # 단어(키)와 해당 인덱스(밸류)를 매핑할 딕셔너리
    bow = []  # BoW를 저장할 리스트

    for word in tokenized_document:
        if word not in word_to_index.keys():
            # 단어가 처음 등장한 경우, 인덱스를 부여하고 BoW에 1을 추가
            word_to_index[word] = len(word_to_index)
            bow.insert(len(word_to_index) - 1, 1)
        else:
            # 이미 등장한 단어의 경우, 해당 인덱스 위치의 BoW 값에 1을 추가
            index = word_to_index.get(word)
            bow[index] = bow[index] + 1

    return word_to_index, bow

In [ ]:
doc1 = "벡터 공간 모델은 텍스트 문서를 나타내는 대수적인 모델이다."

vocab, bow = build_bag_of_words(doc1)

print('vocabulary :', vocab)
print('bag of words vector :', bow)

In [ ]:
#doc2 = "카운트 기반 표현에는 단순 빈도를 사용하는 BoW, DTM이 있다."
doc2 = "카운트 기반 표현에는 단순 표현인 카운트를 사용하는 BoW, DTM이 있다."

vocab, bow = build_bag_of_words(doc2)

print('vocabulary :', vocab)
print('bag of words vector :', bow)

In [ ]:
doc3 = "단순 빈도 표현의 한계점을 보완하기 위해 단어의 가중치를 반영하는 TF-IDF 기법이 있다."

vocab, bow = build_bag_of_words(doc3)

print('vocabulary :', vocab)
print('bag of words vector :', bow)

In [ ]:
doc4 = doc1 + " " + doc2 + " " + doc3

vocab, bow = build_bag_of_words(doc4.lower())

print('vocabulary :', vocab)
print('bag of words vector :', bow)

# **2. TF-IDF**

## **2-1. 라이브러리 활용**

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

doc1 = '먹고 싶은 사과'
doc2 = '먹고 싶은 바나나'
doc3 = '길고 노란 바나나 바나나'
doc4 = '저는 과일이 좋아요'

docs = [doc1, doc2, doc3, doc4]

# TfidfVectorizer 초기화
vectorizer = TfidfVectorizer()

# 문서를 TF-IDF 행렬로 변환
tfidf_matrix = vectorizer.fit_transform(docs)

# TF-IDF 행렬을 array로 저장
tfidf_scores = tfidf_matrix.toarray()

# 특성 이름(단어) 가져오기
feature_names = vectorizer.get_feature_names_out()

# 결과를 표시하기 위한 pandas DataFrame 생성
df_tfidf = pd.DataFrame(tfidf_scores, columns=feature_names)

# 문서 텍스트를 담은 컬럼 추가
df_tfidf['문서'] = docs

In [ ]:
tfidf_scores

array([[0.        , 0.        , 0.        , 0.52640543, 0.        ,
        0.66767854, 0.52640543, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.57735027, 0.57735027,
        0.        , 0.57735027, 0.        , 0.        ],
       [0.        , 0.47212003, 0.47212003, 0.        , 0.7444497 ,
        0.        , 0.        , 0.        , 0.        ],
       [0.57735027, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.57735027, 0.57735027]])

In [ ]:
df_tfidf

,과일이,길고,노란,먹고,바나나,사과,싶은,저는,좋아요,문서
0,0.00000,0.00000,0.00000,0.526405,0.00000,0.667679,0.526405,0.00000,0.00000,먹고 싶은 사과
1,0.00000,0.00000,0.00000,0.577350,0.57735,0.000000,0.577350,0.00000,0.00000,먹고 싶은 바나나
2,0.00000,0.47212,0.47212,0.000000,0.74445,0.000000,0.000000,0.00000,0.00000,길고 노란 바나나 바나나
3,0.57735,0.00000,0.00000,0.000000,0.00000,0.000000,0.000000,0.57735,0.57735,저는 과일이 좋아요

## **2-2. 직접구현**

In [ ]:
import pandas as pd
from math import log

doc1 = '먹고 싶은 사과'
doc2 = '먹고 싶은 바나나'
doc3 = '길고 노란 바나나 바나나'
doc4 = '저는 과일이 좋아요'

docs = [doc1, doc2, doc3, doc4]


# 총 문서의 수
D = len(docs)

# 문서 d 내에서 단어 t의 빈도(TF)를 계산
def tf(t, d):
    return d.count(t)

# 단어 t의 역문서 빈도(IDF)를 계산
def idf(t):
    df = 0
    for doc in docs:
        df += t in doc  # doc에 t가 있는지 확인
    return log(D / (df + 1))

# TF-IDF 점수 계산
def tfidf(t, d):
    return tf(t, d) * idf(t)

In [ ]:
# 문서 내에 등장하는 단어의 집합
vocas = list(set(w for doc in docs for w in doc.split()))
vocas.sort()

vocas

['과일이', '길고', '노란', '먹고', '바나나', '사과', '싶은', '저는', '좋아요']

In [ ]:
result = []  # 결과를 저장할 리스트

for doc in docs:
    result.append([])
    for voca in vocas:
        result[-1].append(tf(voca, doc))  # TF 값을 결과에 추가

tf_score = pd.DataFrame(result, columns=vocas)

In [ ]:
result

[[0, 0, 0, 1, 0, 1, 1, 0, 0],
 [0, 0, 0, 1, 1, 0, 1, 0, 0],
 [0, 1, 1, 0, 2, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 1, 1]]

In [ ]:
tf_score

   과일이  길고  노란  먹고  바나나  사과  싶은  저는  좋아요
0    0   0   0   1    0   1   1   0    0
1    0   0   0   1    1   0   1   0    0
2    0   1   1   0    2   0   0   0    0
3    1   0   0   0    0   0   0   1    1

In [ ]:
result = []  # 결과를 저장할 리스트

for voca in vocas:
    result.append(idf(voca))  # IDF 값을 결과에 추가

idf_score = pd.DataFrame(result, index=vocas, columns=["IDF"])

In [ ]:
idf_score

          IDF
과일이  0.693147
길고   0.693147
노란   0.693147
먹고   0.287682
바나나  0.287682
사과   0.693147
싶은   0.287682
저는   0.693147
좋아요  0.693147

In [ ]:
result = []  # 결과를 저장할 리스트

for doc in docs:
    result.append([])
    for voca in vocas:
        result[-1].append(tfidf(voca, doc))  # TF-IDF 값을 결과에 추가

tfidf_score = pd.DataFrame(result, columns=vocas)

In [ ]:
tfidf_score

,과일이,길고,노란,먹고,바나나,사과,싶은,저는,좋아요
0,0.000000,0.000000,0.000000,0.287682,0.000000,0.693147,0.287682,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.287682,0.287682,0.000000,0.287682,0.000000,0.000000
2,0.000000,0.693147,0.693147,0.000000,0.575364,0.000000,0.000000,0.000000,0.000000
3,0.693147,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.693147,0.693147

# **3. 텍스트 벡터 유사도**

## **3-1. 라이브러리 활용**

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

doc1 = '먹고 싶은 사과'
doc2 = '먹고 싶은 바나나'
doc3 = '길고 노란 바나나 바나나'
doc4 = '저는 과일이 좋아요'

docs = [doc1, doc2, doc3, doc4]

# 모든 문서를 BoW 행렬로 변환
vectorizer = CountVectorizer()
bow_matrix = vectorizer.fit_transform(docs)

# 문서를 TF-IDF 행렬로 변환
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(docs)

In [ ]:
# 모든 문서(BoW) 사이의 코사인 유사도 계산
cosine_similarities = cosine_similarity(bow_matrix)

# 코사인 유사도 행렬 출력
df_cosine_similarities = pd.DataFrame(cosine_similarities, columns=docs, index=docs)

In [ ]:
df_cosine_similarities

               먹고 싶은 사과  먹고 싶은 바나나  길고 노란 바나나 바나나  저는 과일이 좋아요
먹고 싶은 사과       1.000000   0.666667       0.000000         0.0
먹고 싶은 바나나      0.666667   1.000000       0.471405         0.0
길고 노란 바나나 바나나  0.000000   0.471405       1.000000         0.0
저는 과일이 좋아요     0.000000   0.000000       0.000000         1.0

In [ ]:
# 모든 문서(TF-IDF) 사이의 코사인 유사도 계산
cosine_similarities = cosine_similarity(tfidf_matrix)

# 코사인 유사도 행렬 출력
df_cosine_similarities = pd.DataFrame(cosine_similarities, columns=docs, index=docs)

In [ ]:
df_cosine_similarities

               먹고 싶은 사과  먹고 싶은 바나나  길고 노란 바나나 바나나  저는 과일이 좋아요
먹고 싶은 사과       1.000000   0.607841       0.000000         0.0
먹고 싶은 바나나      0.607841   1.000000       0.429808         0.0
길고 노란 바나나 바나나  0.000000   0.429808       1.000000         0.0
저는 과일이 좋아요     0.000000   0.000000       0.000000         1.0

## **3-2. 직접 구현**

### **코사인 유사도**

In [ ]:
import numpy as np
from numpy import dot
from numpy.linalg import norm

def cos_sim(A, B):
    return dot(A, B) / (norm(A) * norm(B))

doc1 = np.array([0,1,1,1])
doc2 = np.array([1,0,1,1])
doc3 = np.array([2,0,2,2])

print('문서1과 문서2의 유사도 :',cos_sim(doc1, doc2))
print('문서1과 문서3의 유사도 :',cos_sim(doc1, doc3))
print('문서2와 문서3의 유사도 :',cos_sim(doc2, doc3))

문서1과 문서2의 유사도 : 0.6666666666666667
문서1과 문서3의 유사도 : 0.6666666666666667
문서2와 문서3의 유사도 : 1.0000000000000002

### **유클리드 유사도**

In [ ]:
import numpy as np

def dist(x,y):
    return np.sqrt(np.sum((x-y)**2))

doc1 = np.array((2,3,0,1))
doc2 = np.array((1,2,3,1))
doc3 = np.array((2,1,2,2))
docQ = np.array((1,1,0,1))

print('문서1과 문서Q의 거리 :',dist(doc1,docQ))
print('문서2과 문서Q의 거리 :',dist(doc2,docQ))
print('문서3과 문서Q의 거리 :',dist(doc3,docQ))

print('\n')

print('문서1과 문서Q의 거리 :',np.linalg.norm(doc1 - docQ))
print('문서2과 문서Q의 거리 :',np.linalg.norm(doc2 - docQ))
print('문서3과 문서Q의 거리 :',np.linalg.norm(doc3 - docQ))

문서1과 문서Q의 거리 : 2.23606797749979
문서2과 문서Q의 거리 : 3.1622776601683795
문서3과 문서Q의 거리 : 2.449489742783178


문서1과 문서Q의 거리 : 2.23606797749979
문서2과 문서Q의 거리 : 3.1622776601683795
문서3과 문서Q의 거리 : 2.449489742783178

### **자카드 유사도**

In [ ]:
doc1 = "apple banana everyone like likey watch card holder"
doc2 = "apple banana coupon passport love you"

# 토큰화
tokenized_doc1 = doc1.split()
tokenized_doc2 = doc2.split()

print('문서1 :',tokenized_doc1)
print('문서2 :',tokenized_doc2)

문서1 : ['apple', 'banana', 'everyone', 'like', 'likey', 'watch', 'card', 'holder']
문서2 : ['apple', 'banana', 'coupon', 'passport', 'love', 'you']

In [ ]:
union = set(tokenized_doc1).union(set(tokenized_doc2))
print('문서1과 문서2의 합집합 :',union)

문서1과 문서2의 합집합 : {'likey', 'holder', 'watch', 'apple', 'love', 'passport', 'banana', 'card', 'coupon', 'like', 'you', 'everyone'}

In [ ]:
intersection = set(tokenized_doc1).intersection(set(tokenized_doc2))
print('문서1과 문서2의 교집합 :',intersection)

문서1과 문서2의 교집합 : {'banana', 'apple'}

In [ ]:
print('자카드 유사도 :',len(intersection)/len(union))

자카드 유사도 : 0.16666666666666666